<?php

namespace Tests\Tree6bee\Queue;

use Tree6bee\Queue\Drivers\Beanstalkd;
use Tree6bee\Queue\Queue;
use Tree6bee\Queue\Worker;

class QueueTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Queue
     */
    private $queue;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $host = 'localhost';
        $port = 11300;
        $this->queue = new Queue(new Beanstalkd($host, $port));
    }

    public function testDispatch()
    {
        $job = new Jobs\ExampleJob([1, 2, 3, 0, 6]);

        $this->queue->push($job);
    }

    public function _testLater()
    {
        $job = new Jobs\ExampleJob([1, 2, 3, 0, 6]);

        $this->queue->later(60, $job);
    }

    public function testRunNextJob()
    {
        $worker = new Worker($this->queue);

        $worker->runNextJob();
    }
}
